- hosts: ScaleWay_Docker
  serial: 3
  name: "** LOCALHOST **"
  remote_user: root
  gather_facts: True

  tasks:
   - name: Mise à jour du dossier depuis GitHub
     git: repo=git@github.com:MrRaph/WoW_AH_Importer.git dest=/data/WoW/AH_Importer accept_hostkey=True
     run_once: True

   - name: Build de l'image
     command: docker-compose build
     args:
       chdir: /data/WoW/AH_Importer

   - name: Mise à jour des containers
     command: docker-compose up -d
     environment:
       DOCKER_HOST: ":4000"
     args:
       chdir: /data/WoW/AH_Importer
     run_once: True
