- hosts: ScaleWay_Docker
  serial: 3
  name: "** LOCALHOST **"
  remote_user: root
  gather_facts: True

  tasks:
   - name: Get stuff from git
     git: repo=git@github.com:MrRaph/WoW_AH_Importer.git dest=/data/WoW/AH_Importer accept_hostkey=True
     run_once: True
   - name: Build de l'image
     command: docker-compose build
     args:
       chdir: /data/WoW/AH_Importer
   - name: Build de l'image
     command: docker-compose up -d
     args:
       chdir: /data/WoW/AH_Importer
     run_once: True
